spring:
  application:
    name: test-service
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: example
      password: example
  cache:
    type: couchbase
    cache-names: players

server:
  port: 8080

